### PR TITLE
Canonicalized versions of withSystemTempDirectory and withTempDirectory

### PR DESCRIPTION
**Pull request by robstewart57**
See https://github.com/batterseapower/temporary/pull/16

### CODE REVIEW

**Comment by robstewart57** [comment]
@feuerbach would you mind pinging me once this commit is reflected as a version bump on hackage, please?

**Comment by UnkindPartition** [comment]
Sure, will do. But could you clarify the docs (as I asked in the other PR)?

**Comment by robstewart57** [comment]
Thanks. I've added documentation in 7f0d514f80921d7ef11690a412c8ff411f034d7e , appended to this PR.

**Comment by christian-marie** [comment]
+1 to this PR, I had some tests failing on OSX only because it puts its temp files in a symlinked /var/. Glad this is getting done.

**Comment by UnkindPartition** [comment]
I guess I never got a response from @robstewart57 on my question about `withCanonicalizedSystemTempDirectory`, and this PR stalled. @christian-marie perhaps you could review the commits and let me know what you think?

**Comment by UnkindPartition** [comment]
@christian-marie also, feel free to prepare your own version with the spaces fixed etc. No need to create a new PR, just point me to your branch here and I'll merge it once we reach a consensus.

**Comment by christian-marie** [comment]
Feeling so free to do so, but effort is concentrated elsewhere.

**Comment by christian-marie** [comment]
Besides, this need not be a race. @robsteward57 may yet lay claim to this.

**Comment by robstewart57** [comment]
Indeed, @robstewart57 may :-)

I'm seeing the emails. Busy today, I'll address tomorrow or Monday.

**Comment by UnkindPartition** [comment]
@robstewart57 starting from v.1.2.1, the system temporary directory (`TMPDIR`) is canonicalized automatically by all functions that access it.

**Pull request closed without merging**
